// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/ws.ts";
import * as $2 from "./routes/wsfrontend.ts";
import * as $$0 from "./islands/ChartDisplay.tsx";
import * as $$1 from "./islands/Clock.tsx";
import * as $$2 from "./islands/CountDownCircle.tsx";
import * as $$3 from "./islands/Counter.tsx";
import * as $$4 from "./islands/ServerStatusTable.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/ws.ts": $1,
    "./routes/wsfrontend.ts": $2,
  },
  islands: {
    "./islands/ChartDisplay.tsx": $$0,
    "./islands/Clock.tsx": $$1,
    "./islands/CountDownCircle.tsx": $$2,
    "./islands/Counter.tsx": $$3,
    "./islands/ServerStatusTable.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
